### ISSUE TITLE
Happy to be the new maintainer

### ISSUE THREAD

**Issue by scottmessinger** [elixir-mongo/mongodb_ecto#177]
Hi! 

We're working on a fork of mongodb_ecto to be compatible with Ecto 3.6. It looks like this repo hasn't received much love since it was transferred from @ankhers and we'd be happy to take ownership of it and push it forward.

Let me know if you'd be interested!
Scott

**Comment by justinmorrow** [comment]
This is awesome! I'm looking forward to seeing what you come up with. 

Any idea on a timeline for the update? And maybe a link to the fork too? I mainly want to keep tabs on upcoming changes so we know when/if we should upgrade. I might contribute a PR too for anything relevant to my work! 

Just as an example: Right now I'm particularly interested in getting mongodb + mongodb_ecto "working" with `Ecto.Adapters.SQL.Sandbox`/`Phoenix.Ecto.SQL.Sandbox` — specifically for running E2E tests with a tool like Cypress against a live site without mucking up the production DB. I only just started sorting out how I could go about that though, so really this is just an example (not a proposal). Even if I find a solution that works for me, I'm doubtful it'll be one that generalizes well enough to merge in. Maybe I'll surprise myself though.

Regardless, thanks for taking this on, Scott! Much appreciated :)

**Comment by scottmessinger** [comment]
@justinmorrow No worries! The fork is here: https://github.com/commoncurriculum/mongodb_ecto/tree/ecto3

My goal is to wrap up this by the end of next Friday. I appear to have it working, except for this issue:  https://github.com/elixir-ecto/ecto/issues/3633

Also, I'm building off a commit made by @aselder -- he did a bunch of work a couple years ago. I've been working on making the test suite pass.

We'd like to start using this in production in the next month, so we're certainly motivated!

**Comment by aram0112** [comment]
Hello @scottmessinger! I was looking into using MongoDB with the Phoenix Framework and Ecto 3.6 and I was wondering if you had a production ready version of the Ecto adaptor. I was looking through your fork and very much appreciate the work you put in!

**Comment by joeapearson** [comment]
@hauleth @deadtrickster please can you help with this?

@scottmessinger (and others) have kindly put in some work and we'd really like to start using it if we can.  We're in a similar boat where we'd very much like Mongo Ecto support.

I'm happy to volunteer to be a maintainer too if that helps.  Given that there haven't been any updates to this repo in a while,  it's difficult to see a choice other than forking this repo and publishing a completely separate package, which doesn't seem like a great solution for anyone!

I understand that maintaining OS repos is a big (and largely thankless) task.  I'm not trying to sound unappreciative of your work, but it would be great to find a decent way forward so that the community can keep this project moving.

**Comment by johnnyshields** [comment]
👍 +1 for @scottmessinger so we can move forward

**Comment by madurangae** [comment]
This is a great news! Thank you!

**Comment by scottmessinger** [comment]
We now have the repo transferred to this organization and we're making improvements! We also have the hex.pm ownership transferred. @ankhers has been invaluable in making all this happen -- thanks so much!!!
